tap "asmvik/formulae", trusted: { formulae: ["yabai", "skhd"] }
tap "FelixKratz/formulae", trusted: { formulae: ["sketchybar", "borders"] }

brew "stow"
brew "git"
brew "git-lfs"
brew "gh"
brew "ssh-copy-id"
brew "neovim"
brew "tmux"
brew "starship"
brew "zoxide"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "bat"
brew "jq"
brew "fastfetch"
brew "openvpn"
brew "imagemagick"
brew "luarocks"
brew "node"
brew "yarn"
brew "go"
brew "python"
brew "llvm"
brew "shellcheck"
brew "shfmt"
brew "pngpaste"
brew "coreutils"
brew "gnu-sed"
brew "wget"

brew "asmvik/formulae/yabai"
brew "asmvik/formulae/skhd"
brew "FelixKratz/formulae/sketchybar"
brew "FelixKratz/formulae/borders"

cask "kitty"
cask "firefox"
cask "telegram"
cask "font-jetbrains-mono-nerd-font"
cask "codex"
